apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: darianbr97/ticket
          env:
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: TICKET_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ticket-db-connection
                  key: TICKET_MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-srv
spec:
  type: ClusterIP
  selector:
    app: ticket
  ports:
    - name: ticket
      protocol: TCP
      port: 4001
      targetPort: 4001
